### ISSUE TITLE
Property: "Force" | Expected: true | Actual: null. 

### ISSUE THREAD

**Issue by nl2rma** [dsccommunity/GPRegistryPolicyDsc#41]
I am deploying Azure Recomended settings through Azure Policy Guest Configuration.
Some settings dont override and I have found a property to user "Force"
I added this to the policy:

Configuration WindowsHardeningSettings
{
        Import-DSCResource -ModuleName 'PSDesiredStateConfiguration'
	Import-DscResource -ModuleName 'PSDscResources'
        Import-DSCResource -ModuleName 'SecurityPolicyDSC'

    Node localhost {
		Registry 'EnableMulticast' {
			Ensure     = 'Present'
			Force      = $true
			Key        = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient'
			ValueName  = 'EnableMulticast'
			ValueType  = 'DWord'
			ValueData  = '1'
		}
	}	
}

But in the Guest Assignment I see the setting is still not corrected with the reason:

Name
Compliance state
Reason
[Registry]EnableMulticast
Non-compliant
 Property: "Force" | Expected: true | Actual: null. 
Property: "ValueData" | Expected: ["1"] | Actual: ["0"]. 

I tried replacing $true with [bool]"$true" also, but the registery key is not changed and the Reason remains the same.
This case is on a  Windows server 2022, but I am experiencing same behaviour on Server 2016.

Any idea why the property 'Force' is not working

**Comment by johlju** [comment]
The question is regarding `Registry` DSC resource which is part of https://github.com/PowerShell/PSDscResources. But suggest you try xPSDesiredStateConfiguration module instead if PSDscResources.

Closing this issue as `Registry` is not part of this repo.
