### ISSUE TITLE
Add release tag to the CI pipeline on deploy

### ISSUE THREAD

**Issue by johlju** [dsccommunity/GPRegistryPolicyDsc#5]
When we merge a new release into the master branch it will automatically deploy to PowerShell Gallery, but there will not be GitHub Release. We should try to automate this step to.

**Comment by johlju** [comment]
@jcwalker how did you to the release tag, I see you solved that one for the last release? Can we automate it easily?

**Comment by jcwalker** [comment]
@johlju I manually created the tag.  I'm not sure on the specifics on how to automate it.

**Comment by johlju** [comment]
What do you do to create the tag?

**Comment by jcwalker** [comment]
I simply followed the instructions [here](https://help.github.com/en/articles/creating-releases)

**Comment by johlju** [comment]
Ah cool! I think we could automate this with https://github.com/pcgeek86/PSGitHub (or some other tool), but it looks like we need to have a personal access token for an account with enough permission to create released. 🤔

**Comment by gaelcolas** [comment]
I've been working on that ;)
You can leave this to me.

**Comment by johlju** [comment]
@gaelcolas Cool! Thank you!

**Comment by johlju** [comment]
Working on getting this repo to the new CI pipeline

**Comment by johlju** [comment]
@jcwalker from now on it will release a preview version on every merge to branch `master` unless you use `[skip ci]` in the commit title or description. If you want to release a full version you do the following https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery#publish-the-next-full-version
